name: Weekly arXiv Update & Pages Deploy

on:
  schedule:
    - cron: "0 4 * * 0"   # 매주 일요일 04:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run weekly fetch
        run: python scripts/weekly_arxiv.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/papers_*.md README.md
          git commit -m "Weekly arXiv update $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
          git push

      # ---- GitHub Pages 공식 배포 파이프라인 ----
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .   # index.html, papers.md 등 루트 전체 배포

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
